const engine=new BotanicaEngine({seed:0xB07A,bpm:120});
const CORE={running:false,timer:null};
const MIDI={out:null,noteOn(n,v,ch){if(!this.out||engine.mute||n<0||n>127)return;this.out.send([0x8F+ch,n,Math.max(1,Math.min(127,v))]);},noteOff(n,ch){if(!this.out||n<0||n>127)return;this.out.send([0x7F+ch,n,0]);}};
const activeNotes={};
function scheduleNote(event){setTimeout(()=>{if(!CORE.running||engine.mute)return;const note=event.note,ch=1;if(activeNotes[note])clearTimeout(activeNotes[note]);else MIDI.noteOn(note,event.velocity,ch);activeNotes[note]=setTimeout(()=>{MIDI.noteOff(note,ch);delete activeNotes[note];},event.durationMs);lg('♩ '+event.label+' vel:'+event.velocity+(event.source==='blossom'?' · blossom':''));showDisp(event.label);},Math.max(0,event.delayMs));}
function allOff(){for(const n in activeNotes){MIDI.noteOff(parseInt(n),1);clearTimeout(activeNotes[n]);delete activeNotes[n];}for(let n=0;n<128;n++)MIDI.noteOff(n,1);}
async function initMIDI(){if(!navigator.requestMIDIAccess){document.getElementById('warn').style.display='block';dot('midi','err');return;}try{const ma=await navigator.requestMIDIAccess();dot('midi','on');document.getElementById('t-midi').textContent='MIDI OK';function pick(){const o=[...ma.outputs.values()];if(o.length){MIDI.out=o[0];document.getElementById('t-out').textContent='→ '+MIDI.out.name.substring(0,16);dot('out','on');lg('MIDI: '+MIDI.out.name);}}pick();ma.onstatechange=pick;}catch(e){document.getElementById('warn').style.display='block';dot('midi','err');}}
function startSeq(){if(CORE.running)return;CORE.running=true;engine.resetPlayback();dot('clk','on');document.getElementById('t-clk').textContent='RUNNING';tick();}
function stopSeq(){CORE.running=false;if(CORE.timer)clearTimeout(CORE.timer);allOff();dot('clk','');document.getElementById('t-clk').textContent='STOPPED';document.getElementById('dv-step').textContent='— / —';}
function tick(){if(!CORE.running)return;const result=engine.tick();document.getElementById('dv-step').textContent=(result.step+1)+'/'+result.length;result.events.forEach(scheduleNote);if(result.evolved)lg('↻ tone evolve');updatePD();CORE.timer=setTimeout(tick,Math.max(10,result.stepMs));}
let dispTimer=null;function showDisp(label){document.getElementById('dv').textContent=label;document.getElementById('dl').textContent='';if(dispTimer)clearTimeout(dispTimer);dispTimer=setTimeout(()=>{const state=engine.getState();document.getElementById('dv').textContent=state.seasonLabel;document.getElementById('dl').textContent='SEASON';},2000);}function updatePD(){document.getElementById('dv-pat').textContent=engine.getPatternDisplay();}function dot(id,st){const d=document.getElementById('d-'+id);if(d)d.className='dot'+(st==='on'?' on':st==='err'?' err':'');}function lg(msg){const l=document.getElementById('log');const d=document.createElement('div');d.className='ll';d.textContent=msg;l.appendChild(d);while(l.children.length>4)l.removeChild(l.firstChild);}
function setSeason(i){engine.setSeason(i);document.querySelectorAll('.sbtn').forEach((b,j)=>b.classList.toggle('active',j===i));updatePD();const state=engine.getState();showDisp(state.seasonLabel);lg('Season: '+state.seasonName);}
function seedPattern(){if(!engine.seedPattern()){lg('PATTERN LOCKED');return;}updatePD();showDisp('PAT');lg('⟳ pattern seed');}
function seedTones(){if(!engine.seedTones()){lg('TONES LOCKED');return;}updatePD();showDisp('TON');lg('⟳ tones seed');}
function toggleLock(t){if(t==='pattern'){const locked=engine.togglePatternLock();document.getElementById('btn-plock').classList.toggle('locked',locked);document.getElementById('led-plock').classList.toggle('on',locked);lg(locked?'PATTERN LOCKED':'PATTERN FREE');}else{const locked=engine.toggleToneLock();document.getElementById('btn-tlock').classList.toggle('locked',locked);document.getElementById('led-tlock').classList.toggle('on',locked);lg(locked?'TONES LOCKED':'TONES FREE');}}
function toggleEuclid(){const active=engine.toggleEuclid();document.getElementById('btn-euclid').classList.toggle('active',active);document.getElementById('led-euc').classList.toggle('on',active);updatePD();lg(active?'EUCLID':'ORGANIC');}
function toggleMute(){const muted=engine.toggleMute();document.getElementById('btn-mute').classList.toggle('muted',muted);document.getElementById('led-mute').classList.toggle('mon',muted);if(muted)allOff();}
function setRamp(m){engine.setRamp(m);['down','up'].forEach(x=>document.getElementById('mb-'+x).classList.toggle('active',x===m));}
function setPitch(m){const state=engine.getState();if(state.blossomPitchMode===m){engine.setPitchMode('none');['arp','octdown','octup'].forEach(x=>document.getElementById('mb-'+x).classList.remove('active'));}else{engine.setPitchMode(m);['arp','octdown','octup'].forEach(x=>document.getElementById('mb-'+x).classList.toggle('active',x===m));}}
function makeKnob(cfg){const sz=cfg.size||46,r=sz/2-4,cx=sz/2,cy=sz/2;let val=cfg.val;const wrap=document.createElement('div');wrap.className='kw';const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width',sz);svg.setAttribute('height',sz);svg.setAttribute('viewBox',`0 0 ${sz} ${sz}`);const bg=document.createElementNS('http://www.w3.org/2000/svg','circle');bg.setAttribute('cx',cx);bg.setAttribute('cy',cy);bg.setAttribute('r',r);bg.setAttribute('fill','#2A2A26');bg.setAttribute('stroke','#4A4A42');bg.setAttribute('stroke-width','2');const mk=document.createElementNS('http://www.w3.org/2000/svg','line');mk.setAttribute('x1',cx);mk.setAttribute('y1',cy);mk.setAttribute('stroke','#B8A96A');mk.setAttribute('stroke-width','2.5');mk.setAttribute('stroke-linecap','round');svg.appendChild(bg);svg.appendChild(mk);const lbl=document.createElement('div');lbl.className='klabel';lbl.textContent=cfg.label;const val_el=document.createElement('div');val_el.className='kval';val_el.id='kv-'+cfg.id;wrap.appendChild(svg);wrap.appendChild(lbl);wrap.appendChild(val_el);function setMarker(v){const pct=(v-cfg.min)/(cfg.max-cfg.min),angle=(-135+pct*270)*Math.PI/180;mk.setAttribute('x2',cx+Math.sin(angle)*r);mk.setAttribute('y2',cy-Math.cos(angle)*r);}let dragging=false,sy=0,sv=0;wrap.addEventListener('mousedown',e=>{dragging=true;sy=e.clientY;sv=val;e.preventDefault();const onMove=ev=>{if(!dragging)return;val=Math.max(cfg.min,Math.min(cfg.max,sv+(sy-ev.clientY)*(cfg.max-cfg.min)/120));setMarker(val);cfg.onchange(val);updatePD();};const onUp=()=>{dragging=false;document.removeEventListener('mousemove',onMove);document.removeEventListener('mouseup',onUp);};document.addEventListener('mousemove',onMove);document.addEventListener('mouseup',onUp);});setMarker(val);return{el:wrap,init(){cfg.onchange(val);}};}
function addKnobs(containerId,defs){const row=document.getElementById(containerId);if(!row)return;defs.forEach(cfg=>{const {el,init}=makeKnob(cfg);row.appendChild(el);init();});}
function buildAll(){addKnobs('pat-pots',[{id:'steps',label:'LENGTH',min:1,max:16,val:8,size:42,onchange(v){engine.setParam('length',v);document.getElementById('kv-steps').textContent=Math.round(v);}},{id:'hits',label:'HITS',min:1,max:16,val:4,size:42,onchange(v){engine.setParam('hits',v);document.getElementById('kv-hits').textContent=Math.min(Math.round(v),engine.len);}},{id:'prune',label:'PRUNE',min:0,max:100,val:100,size:52,onchange(v){engine.setParam('prune',v/100);document.getElementById('kv-prune').textContent=Math.round(v)+'%';}},{id:'prune-rnd',label:'RND',min:0,max:100,val:0,size:34,onchange(v){engine.setParam('pruneRnd',v/100);document.getElementById('kv-prune-rnd').textContent=Math.round(v)+'%';}},{id:'sloppy',label:'SLOPPY',min:0,max:100,val:0,size:52,onchange(v){engine.setParam('sloppy',v/100);document.getElementById('kv-sloppy').textContent=Math.round(v)+'%';}}]);addKnobs('tone-pots',[{id:'root',label:'ROOT',min:-36,max:24,val:0,size:52,onchange(v){engine.setParam('root',v);document.getElementById('kv-root').textContent=engine.getState().rootName;}},{id:'range',label:'RANGE',min:1,max:4,val:2,size:52,onchange(v){engine.setParam('range',v);document.getElementById('kv-range').textContent=Math.round(v)+' oct';}},{id:'evolve',label:'EVOLVE',min:0,max:100,val:0,size:52,onchange(v){engine.setParam('evolve',v/100);document.getElementById('kv-evolve').textContent=Math.round(v)+'%';}}]);addKnobs('blos-pots',[{id:'blossom',label:'AMOUNT',min:0,max:100,val:0,size:52,onchange(v){engine.setParam('blossom',v/100);document.getElementById('kv-blossom').textContent=Math.round(v)+'%';}},{id:'refract',label:'REFRACT',min:0,max:4,val:2,size:52,onchange(v){engine.setParam('refract',v);document.getElementById('kv-refract').textContent=engine.getState().topologyLabel;}},{id:'ref-rnd',label:'RND',min:0,max:100,val:0,size:34,onchange(v){engine.setParam('refractRnd',v/100);document.getElementById('kv-ref-rnd').textContent=Math.round(v)+'%';}},{id:'offset',label:'OFFSET',min:0,max:8,val:0,size:34,onchange(v){engine.setParam('offset',v);document.getElementById('kv-offset').textContent=Math.round(v)+' div';}},{id:'decay',label:'DECAY',min:1,max:16,val:3,size:34,onchange(v){engine.setParam('decay',v);document.getElementById('kv-decay').textContent=Math.round(v)+'×';}}]);}
buildAll();setSeason(0);updatePD();initMIDI();lg('BOTANICA v0.3 engine split ready');lg('▶ PLAY · SEED PATTERN · SEED TONES');
